export const SET_FOOD_CHOICES = 'SET_FOOD_CHOICES';
export const SET_MENU_ITEMS = 'SET_MENU_ITEMS';
export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const SET_EDIT_MENU_ITEM = 'SET_EDIT_MENU_ITEM';
export const SET_EDIT_MENU_OPEN = 'SET_EDIT_MENU_OPEN';
export const SET_DIALOG = 'SET_ALERT_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_ALERT_DIALOG';
export const SET_EDIT_RESTAURANTS = 'CLOSE_ALERT_DIALOG';
export const SET_EDIT_RESTAURANTS_OPEN = 'SET_EDIT_RESTAURANTS_OPEN';
export const SET_SIGN_IN_REG_DIALOG_TYPE = 'SET_SIGN_IN_REG_DIALOG_TYPE';
export const SET_SIGN_IN_REG_DIALOG_TITLE = 'SET_SIGN_IN_REG_DIALOG_TITLE';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const SET_ID_TOKEN = 'SET_ID_TOKEN';
export const SET_CUSTOM_ID = 'SET_CUSTOM_ID';
export const SET_LOGIN_TYPE = 'SET_LOGIN_TYPE';
export const SET_ASSOCIATE_RESTAURANTS = 'SET_ASSOCIATE_RESTAURANTS';

